materias=[
    "ESTÁNDARES Y MÉTRICAS PARA EL DESARROLLO DE SOFTWARE",
    "PRINCIPIOS PARA IoT",
    "DISEÑO DE APPS",
    "ESTRUCTURA DE DATOS APLICADAS",
    "APLICACIONES WEB ORIENTADAS A SERVICIOS",
    "EVALUACIÓN Y MEJORA PARA EL DESARROLLO DE SOFTWARE",
    "FORMACIÓN SOCIOCULTURAL IV",
    "INGLÉS IV"
]
i=0
print(materias[i])