// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/*
* import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
* */
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8ILex9E0YtjhkZ2uPubbPw_8Dw2BB9M',
    appId: '1:843256667369:android:d1c1981848979c4d1ce478',
    messagingSenderId: '843256667369',
    projectId: 'sensor-e8ffe',
    databaseURL: 'https://sensor-e8ffe-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-e8ffe.appspot.com',
  );


  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3gDCdpN7WjcDQzgpd8OzRNUZ5-poEMfg',
    appId: '1:843256667369:web:385932390ba171de1ce478',
    messagingSenderId: '843256667369',
    projectId: 'sensor-e8ffe',
    authDomain: 'sensor-e8ffe.firebaseapp.com',
    databaseURL: 'https://sensor-e8ffe-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-e8ffe.appspot.com',
  );
  static const FirebaseOptions Linux = FirebaseOptions(
    apiKey: 'AIzaSyB3gDCdpN7WjcDQzgpd8OzRNUZ5-poEMfg',
    appId: '1:843256667369:web:385932390ba171de1ce478',
    messagingSenderId: '843256667369',
    projectId: 'sensor-e8ffe',
    authDomain: 'sensor-e8ffe.firebaseapp.com',
    databaseURL: 'https://sensor-e8ffe-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-e8ffe.appspot.com',
  );
}
